version: "3"

services:
  supabase-tensorflow-api:
    image: supabase-tensorflow-api:latest
    networks:
      - supabase-internal
    ports:
      - "localhost:5000:5000"
    environment:
      MODEL_PATH: ""
      SUPABASE_PUBLIC_URL: ${SUPABASE_PUBLIC_URL}
      SUPABASE_SERVICE_ROLE_KEY: ${SUPABASE_SERVICE_ROLE_KEY}

      NVIDIA_VISIBLE_DEVICES: all
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]

networks:
  supabase-internal:
    external: true
